name: spotube
description: Open source Spotify client that doesn't require Premium nor uses Electron! Available for both desktop & mobile!

publish_to: "none"

version: 3.5.0+29

homepage: https://spotube.krtirtho.dev
repository: https://github.com/KRTirtho/spotube

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  args: ^2.3.2
  async: ^2.9.0
  audio_service: ^0.18.9
  audio_session: ^0.1.18
  auto_size_text: ^3.0.0
  buttons_tabbar: ^1.3.6
  cached_network_image: ^3.3.0
  catcher_2: 1.0.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
  dbus: ^0.7.8
  device_info_plus: ^9.0.3
  device_preview: ^1.1.0
  dio: ^5.4.1
  disable_battery_optimization: ^1.1.0+1
  duration: ^3.0.12
  envied: ^0.3.0
  file_selector: ^1.0.1
  fl_query: ^1.0.0
  fl_query_hooks: ^1.0.0
  fl_query_devtools: ^0.1.0
  fluentui_system_icons: ^1.1.189
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_desktop_tools:
    git:
      url: https://github.com/KRTirtho/flutter_desktop_tools.git
      ref: 1f0bec3283626dcbd8ee2f54e238d096d8dea50e
  flutter_displaymode: ^0.6.0
  flutter_feather_icons: ^2.0.0+1
  flutter_hooks: ^0.20.0
  flutter_inappwebview: ^5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.4.10
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^1.1.6
  form_validator: ^2.1.1
  fuzzywuzzy: ^1.1.6
  go_router: 12.1.3 # Stuck on this https://github.com/flutter/flutter/issues/140869
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.3
  html: ^0.15.1
  http: ^1.2.0
  image_picker: ^1.0.4
  intl: ^0.18.0
  introduction_screen: ^3.0.2
  json_annotation: ^4.8.1
  logger: ^2.0.2
  media_kit: ^1.1.3
  media_kit_libs_audio: ^1.0.3
  metadata_god: ^0.5.2+1
  mime: ^1.0.2
  package_info_plus: ^4.1.0
  palette_generator: ^0.3.3
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^11.0.1
  piped_client:
    git:
      url: https://github.com/KRTirtho/piped_client.git
  popover: ^0.2.6+3
  scrobblenaut:
    git:
      url: https://github.com/KRTirtho/scrobblenaut.git
      ref: dart-3-support
  scroll_to_index: ^3.0.1
  sidebarx: ^0.16.3
  shared_preferences: ^2.2.2
  skeleton_text: ^3.0.1
  smtc_windows: ^0.1.1
  stroke_text: ^0.0.2
  system_theme: ^2.1.0
  titlebar_buttons: ^1.0.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  version: ^3.0.2
  visibility_detector: ^0.4.0+2
  window_manager: ^0.3.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      ref: a738913c8ce2c9f47515382d40827e794a334274
      path: plugins/window_size
  youtube_explode_dart: ^2.0.1
  simple_icons: ^7.10.0
  audio_service_mpris: ^0.1.0
  file_picker: ^6.0.0
  jiosaavn: ^0.1.0
  draggable_scrollbar:
    git:
      url: https://github.com/thielepaul/flutter-draggable-scrollbar.git
      ref: cfd570035bf393de541d32e9b28808b5d7e602df
  very_good_infinite_list: ^0.7.1
  gap: ^3.0.1
  sliver_tools: ^0.2.12
  dart_discord_rpc:
    git:
      url: https://github.com/Tommypop2/dart_discord_rpc.git
  html_unescape: ^2.0.0
  wikipedia_api: ^0.1.0
  skeletonizer: ^0.8.0
  app_links: ^3.5.0
  win32_registry: ^1.1.2
  flutter_sharing_intent: ^1.1.0
  flutter_broadcasts: ^0.4.0
  freezed_annotation: ^2.4.1
  spotify: ^0.13.3

dev_dependencies:
  build_runner: ^2.3.2
  envied_generator: ^0.3.0+3
  flutter_distributor: ^0.0.2
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.6.2
  pub_api_client: ^2.4.0
  pubspec_parse: ^1.2.2
  freezed: ^2.4.6

dependency_overrides:
  system_tray: 2.0.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/tutorial/
    - assets/logos/
    - LICENSE

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/spotube-logo.png"
  adaptive_icon_foreground: "assets/spotube-logo-foreground.jpg"
  adaptive_icon_background: "#242832"
  windows:
    generate: true
    image_path: "assets/spotube-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/spotube-logo.png"

flutter_gen:
  output: lib/collections

flutter_native_splash:
  background_image: assets/bengali-patterns-bg.jpg
  image: assets/spotube-logo.png
  branding: assets/branding.png
  android_12:
    image: assets/spotube-logo_android12.png
    branding: assets/branding.png
    color: "#000000"
    icon_background_color: "#000000"
