name: spotube
description: Open source extensible music streaming platform and app, based on BYOMM (Bring your own music metadata) concept

publish_to: "none"

version: 5.1.0+43

homepage: https://spotube.krtirtho.dev
repository: https://github.com/KRTirtho/spotube

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  app_links: ^6.4.0
  args: ^2.5.0
  audio_service: ^0.18.13
  audio_service_mpris: ^0.2.0
  audio_session: ^0.1.19
  auto_route: ^9.3.0+1
  auto_size_text: ^3.0.0
  bonsoir: ^5.1.10
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.2
  desktop_webview_window:
    git:
      path: packages/desktop_webview_window
      url: https://github.com/KRTirtho/flutter-plugins.git
  device_info_plus: ^11.1.1
  dio: ^5.4.3+1
  disable_battery_optimization:
    git:
      url: https://github.com/KRTirtho/Disable-Battery-Optimizations.git
  draggable_scrollbar:
    git:
      ref: cfd570035bf393de541d32e9b28808b5d7e602df
      url: https://github.com/thielepaul/flutter-draggable-scrollbar.git
  drift: ^2.21.0
  duration: ^3.0.12
  encrypt: ^5.0.3
  envied: ^1.0.0
  file_picker: 10.3.3
  file_selector: ^1.0.3
  fluentui_system_icons: ^1.1.234
  flutter:
    sdk: flutter
  flutter_broadcasts:
    git:
      url: https://github.com/KRTirtho/flutter_broadcasts.git
      ref: 63931dfe06733d4fb7452e9981e1f0b23414d97a
  flutter_cache_manager: ^3.3.0
  flutter_discord_rpc: ^1.1.0
  flutter_displaymode: ^0.6.0
  flutter_feather_icons: ^2.0.0+1
  flutter_form_builder: ^9.6.0
  flutter_hooks: ^0.20.5
  flutter_inappwebview: ^6.1.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.5.1
  flutter_sharing_intent: ^1.1.0
  flutter_undraw: ^0.2.1
  form_builder_validators: ^11.1.1
  freezed_annotation: ^2.4.1
  fuzzywuzzy: ^1.1.6
  home_widget: ^0.7.0
  hooks_riverpod: ^2.5.1
  html: ^0.15.1
  html_unescape: ^2.0.0
  http: ^1.2.1
  image_picker: ^1.1.0
  intl: any
  local_notifier: ^0.1.6
  logger: ^2.0.2
  logging: ^1.3.0
  lrc: ^1.0.2
  metadata_god: ^1.1.0
  mime: ^2.0.0
  open_file: ^3.5.10
  package_info_plus: ^6.0.0
  palette_generator: ^0.3.3
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  riverpod: ^2.5.1
  scrobblenaut:
    git:
      ref: dart-3-support
      url: https://github.com/KRTirtho/scrobblenaut.git
  scroll_to_index: ^3.0.1
  shadcn_flutter: ^0.0.47
  shared_preferences: ^2.2.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  simple_icons: ^10.1.3
  skeletonizer: ^2.1.0+1
  sliding_up_panel: ^2.0.0+1
  sliver_tools: ^0.2.12
  smtc_windows: ^1.1.0
  sqlite3: ^2.4.3
  sqlite3_flutter_libs: ^0.5.23
  timezone: ^0.10.0
  titlebar_buttons: ^1.0.0
  tray_manager: ^0.5.0
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  version: ^3.0.2
  very_good_infinite_list: ^0.9.0
  visibility_detector: ^0.4.0+2
  web_socket_channel: ^3.0.1
  wikipedia_api: ^0.1.0
  win32_registry: ^1.1.5
  window_manager: ^0.4.3
  youtube_explode_dart: ^3.0.0
  yt_dlp_dart:
    git:
      url: https://github.com/KRTirtho/yt_dlp_dart.git
      ref: 4e5310e14af74bdbb51e2a4766e66d6c6a2562a8
  flutter_new_pipe_extractor:
    git:
      url: https://github.com/KRTirtho/flutter_new_pipe_extractor.git
  http_parser: ^4.1.2
  collection: any
  archive: ^4.0.7
  hetu_script: ^0.4.2+1
  hetu_std:
    git:
      url: https://github.com/hetu-community/hetu_std.git
      ref: main
  hetu_otp_util:
    git:
      url: https://github.com/hetu-community/hetu_otp_util.git
      ref: main
  hetu_spotube_plugin:
    git:
      url: https://github.com/KRTirtho/hetu_spotube_plugin.git
      ref: main
  get_it: ^8.0.3
  flutter_markdown_plus: ^1.0.3
  pub_semver: ^2.2.0
  change_case: ^1.1.0
  flutter_secure_storage: ^9.2.4
  # Have to use the git version due to unresponsive .move() after .add()
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
  media_kit_libs_audio:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_audio
  base32: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^1.0.0
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.2
  freezed: ^2.5.2
  process_run: ^0.14.2
  pubspec_parse: ^1.3.0
  pub_api_client: ^3.0.0
  io: ^1.0.4
  drift_dev: ^2.21.0
  test: ^1.25.7
  auto_route_generator: ^9.0.0

dependency_overrides:
  bonsoir_android:
    git:
      url: https://github.com/KRTirtho/Bonsoir.git
      path: packages/bonsoir_android
  meta: 1.16.0
  web: ^1.1.0
  flutter_svg: ^2.0.17
  intl: any
  collection: any
  flutter_secure_storage_platform_interface: 2.0.0
  flutter_secure_storage_linux:
    git:
      url: https://github.com/m-berto/flutter_secure_storage.git
      ref: patch-2
      path: flutter_secure_storage_linux
  media_kit_libs_android_audio:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/android/media_kit_libs_android_audio
  media_kit_libs_ios_audio:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/ios/media_kit_libs_ios_audio
  media_kit_libs_macos_audio:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/macos/media_kit_libs_macos_audio
  media_kit_libs_windows_audio:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/windows/media_kit_libs_windows_audio
  media_kit_libs_linux:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/linux/media_kit_libs_linux

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/branding/spotube-logo.png
    - assets/branding/spotube-logo-light.png
    - assets/branding/spotube-logo.ico
    - assets/plugins/spotube-plugin-musicbrainz-listenbrainz/plugin.smplug
    - assets/plugins/spotube-plugin-youtube-audio/plugin.smplug
    - LICENSE
    - packages/flutter_undraw/assets/undraw/access_denied.svg
    - packages/flutter_undraw/assets/undraw/fixing_bugs.svg
    - packages/flutter_undraw/assets/undraw/secure_login.svg
    - packages/flutter_undraw/assets/undraw/explore.svg
    - packages/flutter_undraw/assets/undraw/dreamer.svg
    - packages/flutter_undraw/assets/undraw/happy_music.svg
    - packages/flutter_undraw/assets/undraw/follow_me_drone.svg
    - packages/flutter_undraw/assets/undraw/taken.svg
    - packages/flutter_undraw/assets/undraw/empty.svg
    - packages/flutter_undraw/assets/undraw/no_data.svg
    - packages/flutter_undraw/assets/undraw/process.svg
    - packages/flutter_undraw/assets/undraw/stars.svg
    # hetu script bytecode
    - packages/hetu_std/assets/bytecode/std.out
    - packages/hetu_otp_util/assets/bytecode/otp_util.out
    - packages/hetu_spotube_plugin/assets/bytecode/spotube_plugin.out
  fonts:
    - family: RadixIcons
      fonts:
        - asset: packages/shadcn_flutter/icons/RadixIcons.otf
    - family: BootstrapIcons
      fonts:
        - asset: packages/shadcn_flutter/icons/BootstrapIcons.otf
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf
          style: normal
          weight: 500
    - family: Ubuntu Mono
      fonts:
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-BoldItalic.ttf
          style: italic
          weight: 700

flutter_gen:
  output: lib/collections

flutter_native_splash:
  background_image: assets/bengali-patterns-bg.jpg
  image: assets/spotube-logo.png
  branding: assets/branding.png
  android_12:
    image: assets/spotube-logo_android12.png
    branding: assets/branding.png
    color: "#000000"
    icon_background_color: "#000000"
