name: spotube
description: Open source Spotify client that doesn't require Premium nor uses Electron! Available for both desktop & mobile!

publish_to: "none"

version: 3.1.2+24

homepage: https://spotube.krtirtho.dev
repository: https://github.com/KRTirtho/spotube

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  args: ^2.3.2
  async: ^2.9.0
  audio_service: ^0.18.9
  audio_session: ^0.1.13
  auto_size_text: ^3.0.0
  buttons_tabbar: ^1.3.6
  cached_network_image: ^3.2.2
  catcher:
    git:
      url: https://github.com/ThexXTURBOXx/catcher
  collection: ^1.15.0
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
  dbus: ^0.7.8
  device_info_plus: ^9.0.3
  device_preview: ^1.1.0
  dio: ^5.3.2
  disable_battery_optimization: ^1.1.0+1
  duration: ^3.0.12
  envied: ^0.3.0
  file_selector: ^1.0.1
  fl_query: ^1.0.0-alpha.4
  fl_query_hooks: ^1.0.0-alpha.4+1
  fl_query_devtools: ^0.1.0-alpha.2
  fluentui_system_icons: ^1.1.189
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_desktop_tools:
    git:
      url: https://github.com/KRTirtho/flutter_desktop_tools.git
      ref: 1f0bec3283626dcbd8ee2f54e238d096d8dea50e
  flutter_displaymode: ^0.6.0
  flutter_feather_icons: ^2.0.0+1
  flutter_hooks: ^0.20.0
  flutter_inappwebview: ^5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.1.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^1.1.6
  form_validator: ^2.1.1
  fuzzywuzzy: ^0.2.0
  google_fonts: ^5.1.0
  go_router: ^10.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.1.1
  html: ^0.15.1
  http: ^1.1.0
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  introduction_screen: ^3.0.2
  json_annotation: ^4.8.1
  logger: ^1.1.0
  media_kit: ^1.1.3
  media_kit_libs_audio: ^1.0.1
  metadata_god: ^0.5.0
  mime: ^1.0.2
  package_info_plus: ^4.1.0
  palette_generator: ^0.3.3
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^10.2.0
  piped_client: ^0.1.0
  popover: ^0.2.6+3
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.0.11
  sidebarx: ^0.15.0
  skeleton_text: ^3.0.1
  smtc_windows: ^0.1.0
  spotify: ^0.12.0
  stroke_text: ^0.0.2
  supabase: ^1.9.9
  system_theme: ^2.1.0
  titlebar_buttons: ^1.0.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  version: ^3.0.2
  visibility_detector: ^0.3.3
  window_manager: ^0.3.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      ref: a738913c8ce2c9f47515382d40827e794a334274
      path: plugins/window_size
  youtube_explode_dart: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.2
  envied_generator: ^0.3.0+3
  flutter_distributor: ^0.0.2
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.6.2
  pub_api_client: ^2.4.0
  pubspec_parse: ^1.2.2

dependency_overrides:
  http: ^1.1.0
  system_tray: 2.0.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/tutorial/
    - LICENSE

flutter_launcher_icons:
  android: true
  image_path: "assets/spotube-logo.png"
  adaptive_icon_foreground: "assets/spotube-logo-foreground.jpg"
  adaptive_icon_background: "#242832"
  windows:
    generate: true
    image_path: "assets/spotube-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/spotube-logo.png"

flutter_gen:
  output: lib/collections

flutter_native_splash:
  background_image: assets/bengali-patterns-bg.jpg
  image: assets/spotube-logo.png
  branding: assets/branding.png
  android_12:
    image: assets/spotube-logo_android12.png
    branding: assets/branding.png
    color: "#000000"
    icon_background_color: "#000000"
