display_name: Spotube
icon: assets/branding/spotube-logo.png

keywords:
  - Music
  - Media
  - Streaming
  - YouTube

generic_name: Music Streaming Application
categories:
  - Music
# supported_mime_type:
#   - x-scheme-handler/spotify
