display_name: Spotube
package_name: spotube

maintainer:
  name: Kingkor Roy Tirtho
  email: krtirtho@gmail.com

priority: optional
section: x11
installed_size: 24400

dependencies:
  - mpv
  - libappindicator3-1 | libayatana-appindicator3-1
  - gir1.2-appindicator3-0.1 | gir1.2-ayatanaappindicator3-0.1
  - libsecret-1-0
  - libnotify-bin
  - libjsoncpp25
  - libmpv1 | libmpv2

essential: false
icon: assets/spotube-logo.png

keywords:
  - Music
  - Spotify
  - Media
  - Streaming
  - YouTube

generic_name: Music Streaming Application
categories:
  - Music
