name: Lint

on:
  pull_request:

env:
  FLUTTER_VERSION: 3.35.2

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Dummy Envs
        run: |
          envsubst < .env.example > .env
        env:
          ENABLE_UPDATE_CHECK: true
          LASTFM_API_KEY: xxx
          LASTFM_API_SECRET: xxx
          RELEASE_CHANNEL: nightly
          HIDE_DONATIONS: 0

      - name: Configure repo
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Lint Dart files
        run: |
          dart analyze --no-fatal-warnings
